services:
  - name: formwave-backend
    type: web
    build:
      type: buildpack
      buildpack: nodejs
    instance_type: nano
    regions:
      - fra
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
    scaling:
      min: 1
      max: 1
    health_check:
      http:
        path: /api/health
        port: 8000
    routes:
      - path: /
        port: 8000 